# Generated by Django 3.2 on 2021-04-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('geographical_coordinates', models.CharField(max_length=200)),
                ('temperature_color', models.CharField(max_length=3)),
                ('current_icon', models.CharField(max_length=100)),
                ('last_downloaded', models.DateTimeField(auto_now=True, verbose_name='date downloaded')),
            ],
        ),
    ]
