# Generated by Django 3.2 on 2021-04-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='current_temp',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
