# Generated by Django 3.2 on 2021-05-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_temperature_geographical_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='current_icon',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='current_temp',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='temperature_color',
        ),
        migrations.AddField(
            model_name='temperature',
            name='icon',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='temperature',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
