# Generated by Django 3.2 on 2021-05-31 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20210501_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='last_downloaded',
            new_name='downloaded',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='geographical_coordinates',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='location',
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('voivodeship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voivodeships', to='weather.voivodeship')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('geographical_coordinates', models.CharField(max_length=200, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county', to='weather.country')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counties', to='weather.county')),
            ],
        ),
        migrations.AddField(
            model_name='temperature',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='weather.city'),
            preserve_default=False,
        ),
    ]
