# Generated by Django 3.2 on 2021-05-31 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20210531_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country_related', to='weather.country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='county_related', to='weather.county'),
        ),
        migrations.AlterField(
            model_name='county',
            name='voivodeship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voivodeship_related', to='weather.voivodeship'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_related', to='weather.city'),
        ),
    ]
