# Generated by Django 3.2 on 2021-06-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_alter_pickedcity_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_related_to_country', to='weather.country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_related_to_county', to='weather.county'),
        ),
        migrations.AlterField(
            model_name='county',
            name='voivodeship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='county_related', to='weather.voivodeship'),
        ),
        migrations.AlterField(
            model_name='pickedcity',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='city_related', serialize=False, to='weather.city'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_related', to='weather.city'),
        ),
    ]
