# Generated by Django 3.2 on 2021-06-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_alter_temperature_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='county',
            unique_together={('name', 'voivodeship')},
        ),
    ]
